// GENERATED by tools/gen.py from components/lens/achromat_12mm_c.toml — DO NOT EDIT.
// Edit the .toml, then run `make gen`.
include <../lib/lens/params.scad>

flange_to_rear_vertex = 8.0;
element_d = 12.7;
element_edge_thk = 4.0;
clear_aperture_d = 10.0;
filter_thread = "M30.5x0.5";
hood_style = "round";

include <../lib/lens/dispatch.scad>
