// GENERATED by tools/gen.py from components/camera/generic_29mm_cs.toml — DO NOT EDIT.
// Edit the .toml, then run `make gen`.
include <../lib/camera/params.scad>

mount_type = "CS";
lens_mount_style = "thread";
board_x = 29;
board_y = 29;

include <../lib/camera/dispatch.scad>
