// GENERATED by tools/gen.py from components/camera/generic_29mm_c.toml — DO NOT EDIT.
// Edit the .toml, then run `make gen`.
include <../lib/camera/params.scad>

mount_type = "C";
lens_mount_style = "thread";
board_x = 29;
board_y = 29;
board_hole_pitch_x = 22;
board_hole_pitch_y = 22;

include <../lib/camera/dispatch.scad>
