// GENERATED by tools/gen.py from components/camera/generic_29mm_c_ring.toml — DO NOT EDIT.
// Edit the .toml, then run `make gen`.
include <../lib/camera/params.scad>

mount_type = "C";
lens_mount_style = "ring";
ring_bore_d = 25.6;
ring_depth = 6.0;
ring_grubs = 3;
board_x = 29;
board_y = 29;

include <../lib/camera/dispatch.scad>
