// GENERATED by tools/gen.py from components/vibrometer/vibrometer_smi_650.toml — DO NOT EDIT.
// Edit the .toml, then run `make gen`.
include <../lib/vibrometer/params.scad>

laser_can_d = 9.0;
bpw34_pkg = "leaded";
bpw34_wall = "+Y";

include <../lib/vibrometer/dispatch.scad>
