// GENERATED by tools/gen.py from components/receiver/vibrometer_80mm.toml — DO NOT EDIT.
// Edit the .toml, then run `make gen`.
include <../lib/receiver/params.scad>

element_d = 80;
clear_aperture_d = 74;
focal_length = 150;
focus_nominal = 150;
focus_travel = 25;
fine_travel = 6;
draw_od = 24;
draw_id = 17;
filter_d = 8.0;
filter_clear_d = 6.0;
body_outer_x = 39;
body_outer_y = 39;

include <../lib/receiver/dispatch.scad>
