// GENERATED by tools/gen.py from components/receiver/vibrometer_80mm.toml — DO NOT EDIT.
// Edit the .toml, then run `make gen`.
include <../lib/receiver/params.scad>

mount = "C";
element_d = 80;
clear_aperture_d = 74;
focal_length = 150;
flange_to_optic = 150;
filter_d = 8.0;
filter_thk = 0.55;
filter_clear_d = 6.0;

include <../lib/receiver/dispatch.scad>
