#!/usr/bin/env python3
"""Expand components/*.toml into the SCAD variant stubs and the Make/JSON/README wiring.

    python3 tools/gen.py            # (re)write every generated file
    python3 tools/gen.py --check    # fail (exit 1) if any committed generated file is stale

Source of truth:
    components/_type/<type>.toml    # one per component type (hand-edited)
    components/<type>/<name>.toml   # one per component     (hand-edited)

Generated (never hand-edit):
    scad/variants/<name>.scad       # committed  — Customizer / `make` target per component
    components.json                 # committed  — flat manifest
    build/components.mk             # git-ignored — included by the Makefile
    README.md  (between GENERATED markers)
"""

from __future__ import annotations

import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPONENTS = ROOT / "components"
TYPE_DIR = COMPONENTS / "_type"
VARIANT_DIR = ROOT / "scad" / "variants"
BUILD_MK = ROOT / "build" / "components.mk"
MANIFEST = ROOT / "components.json"
README = ROOT / "README.md"

README_BEGIN = "<!-- BEGIN GENERATED:components -->"
README_END = "<!-- END GENERATED:components -->"

ASSIGN_RE = re.compile(r"^\s*([A-Za-z_]\w*)\s*=")


class GenError(Exception):
    pass


def scad_literal(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, str):
        return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'
    if isinstance(value, list):
        return "[" + ", ".join(scad_literal(v) for v in value) + "]"
    raise GenError(f"unsupported parameter value type: {value!r}")


def params_whitelist(params_file: Path) -> set[str]:
    if not params_file.exists():
        raise GenError(f"params_file not found: {params_file}")
    names = set()
    for line in params_file.read_text().splitlines():
        m = ASSIGN_RE.match(line)
        if m:
            names.add(m.group(1))
    return names


def load_types() -> dict[str, dict]:
    types = {}
    for path in sorted(TYPE_DIR.glob("*.toml")):
        data = tomllib.loads(path.read_text())
        name = path.stem
        for key in ("lib", "entry", "params_file", "parts", "check_parts", "preview_cam"):
            if key not in data:
                raise GenError(f"{path.name}: missing '{key}'")
        data["name"] = name
        data["whitelist"] = params_whitelist(ROOT / data["params_file"])
        types[name] = data
    if not types:
        raise GenError(f"no type defs in {TYPE_DIR}")
    return types


def load_components(types: dict[str, dict]) -> list[dict]:
    comps = []
    for path in sorted(COMPONENTS.glob("*/*.toml")):
        if path.parent.name == "_type":
            continue
        data = tomllib.loads(path.read_text())
        name = path.stem
        tname = data.get("type")
        if tname not in types:
            raise GenError(f"{path}: unknown type {tname!r} (have {sorted(types)})")
        if path.parent.name != tname:
            raise GenError(f"{path}: in {path.parent.name}/ but type = {tname!r}")
        params = data.get("params", {})
        wl = types[tname]["whitelist"]
        bad = sorted(k for k in params if k not in wl)
        if bad:
            raise GenError(
                f"{path}: unknown param(s) {bad} — not assigned in "
                f"{types[tname]['params_file']}"
            )
        comps.append(
            {
                "name": name,
                "type": tname,
                "title": data.get("title", name),
                "params": params,
                "src": path.relative_to(ROOT).as_posix(),
            }
        )
    names = [c["name"] for c in comps]
    dupes = sorted({n for n in names if names.count(n) > 1})
    if dupes:
        raise GenError(f"duplicate component name(s) across types: {dupes}")
    return comps


def variant_scad(comp: dict, types: dict[str, dict]) -> str:
    t = types[comp["type"]]
    lib = Path(t["lib"])
    inc = (lib.relative_to("scad")).as_posix()  # e.g. lib/camera
    lines = [
        f"// GENERATED by tools/gen.py from {comp['src']} — DO NOT EDIT.",
        "// Edit the .toml, then run `make gen`.",
        f"include <../{inc}/params.scad>",
        "",
    ]
    for key, val in comp["params"].items():
        lines.append(f"{key} = {scad_literal(val)};")
    lines += ["", f"include <../{inc}/dispatch.scad>", ""]
    return "\n".join(lines)


def components_mk(comps: list[dict], types: dict[str, dict]) -> str:
    out = ["# GENERATED by tools/gen.py — do not edit. Run `make gen`.", ""]
    out.append("ALL_VARIANTS := " + " ".join(c["name"] for c in comps))
    for tname in sorted(types):
        members = [c["name"] for c in comps if c["type"] == tname]
        out.append(f"VARIANTS_{tname} := " + " ".join(members))
    out.append("")
    jobs = []
    for c in comps:
        t = types[c["type"]]
        n = c["name"]
        out.append(f"PARTS_{n} := " + " ".join(t["parts"]))
        out.append(f"CHECKPARTS_{n} := " + " ".join(t["check_parts"]))
        out.append(f"PREVIEW_CAM_{n} := {t['preview_cam']}")
        out.append(f"TITLE_{n} := {c['title']}")
        out.append("")
        jobs += [f"{n}/{p}" for p in t["check_parts"]]
    # <variant>/<part> tokens for the `make check` shell loop
    out.append("CHECK_JOBS := " + " ".join(jobs))
    out.append("")
    return "\n".join(out)


def manifest_json(comps: list[dict], types: dict[str, dict]) -> str:
    doc = {
        "$comment": "GENERATED by tools/gen.py from components/*.toml — do not edit.",
        "types": {
            n: {k: t[k] for k in ("lib", "entry", "parts", "check_parts")}
            for n, t in sorted(types.items())
        },
        "components": [
            {"name": c["name"], "type": c["type"], "title": c["title"], "params": c["params"]}
            for c in comps
        ],
    }
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def readme_block(comps: list[dict], types: dict[str, dict]) -> str:
    rows = []
    for tname in sorted(types):
        members = [c for c in comps if c["type"] == tname]
        if not members:
            continue
        rows.append(f"### {tname.capitalize()} components\n")
        rows.append("| Variant | Description |")
        rows.append("|---|---|")
        for c in members:
            rows.append(f"| `{c['name']}` | {c['title']} |")
        rows.append("")
    return "\n".join(rows).rstrip() + "\n"


def splice_readme(text: str, block: str) -> str:
    if README_BEGIN not in text or README_END not in text:
        raise GenError(
            f"README.md is missing the {README_BEGIN} / {README_END} markers"
        )
    head, rest = text.split(README_BEGIN, 1)
    _, tail = rest.split(README_END, 1)
    return f"{head}{README_BEGIN}\n{block}{README_END}{tail}"


def targets(comps: list[dict], types: dict[str, dict]) -> dict[Path, str]:
    out: dict[Path, str] = {}
    for c in comps:
        out[VARIANT_DIR / f"{c['name']}.scad"] = variant_scad(c, types)
    out[MANIFEST] = manifest_json(comps, types)
    out[README] = splice_readme(README.read_text(), readme_block(comps, types))
    return out


def main(argv: list[str]) -> int:
    check = "--check" in argv[1:]
    try:
        types = load_types()
        comps = load_components(types)
        committed = targets(comps, types)
        mk = components_mk(comps, types)
    except GenError as e:
        print(f"gen.py: {e}", file=sys.stderr)
        return 2

    # stale committed variant stubs (component removed / renamed)
    known = {p for p in committed if p.parent == VARIANT_DIR}
    orphans = sorted(set(VARIANT_DIR.glob("*.scad")) - known)

    if check:
        stale = [p for p, content in committed.items() if _read(p) != content]
        stale += orphans
        if stale:
            print("gen.py --check: stale generated files (run `make gen`):", file=sys.stderr)
            for p in stale:
                print(f"  {p.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print("gen.py --check: generated files are up to date")
        return 0

    for p, content in committed.items():
        _write(p, content)
    for p in orphans:
        p.unlink()
        print(f"  removed orphan {p.relative_to(ROOT)}")
    _write(BUILD_MK, mk)
    n_by_type = ", ".join(
        f"{sum(c['type'] == t for c in comps)} {t}" for t in sorted(types)
    )
    print(f"gen.py: wrote {len(comps)} components ({n_by_type})")
    return 0


def _read(p: Path) -> str | None:
    return p.read_text() if p.exists() else None


def _write(p: Path, content: str) -> None:
    p.parent.mkdir(parents=True, exist_ok=True)
    if _read(p) != content:
        p.write_text(content)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
